'use strict';

module.exports = (userEmail) => ([{
  'queryName': 'Sample Watchlist - Ransomware 1',
  'description': '50 IPs',
  'createdOn': new Date(),
  'userEmail': userEmail,
  'ips': [
    {
      'ipaddress': '103.224.182.250',
      'threat_potential_score_pct': 84.2,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 7,
      'blacklist_observations': 110,
      'country': 'AU',
      'stateprov': 'Victoria',
      'district': 'Bayside',
      'city': 'Beaumaris',
      'zipcode': '3193',
      'location': '-37.9867,145.035',
      'latitude': -37.9867,
      'longitude': 145.035,
      'timezone_offset': 11,
      'timezone_name': 'Australia/Melbourne',
      'ispname': 'TRELLIAN',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS133618 Trellian Pty Limited',
      ],
    },
    {
      'ipaddress': '103.43.75.87',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'AU',
      'stateprov': 'New South Wales',
      'district': 'Sydney',
      'city': 'Sydney',
      'zipcode': '1001',
      'location': '-33.8675,151.207',
      'latitude': -33.8675,
      'longitude': 151.207,
      'timezone_offset': 11,
      'timezone_name': 'Australia/Sydney',
      'ispname': 'Choopa, LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS20473 Choopa LLC',
      ],
    },
    {
      'ipaddress': '104.131.182.103',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'US',
      'stateprov': 'New Jersey',
      'district': 'Passaic',
      'city': 'Clifton',
      'zipcode': '07014',
      'location': '40.8302,-74.1299',
      'latitude': 40.8302,
      'longitude': -74.1299,
      'timezone_offset': -5,
      'timezone_name': 'America/New_York',
      'ispname': 'DigitalOcean, LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Internet Assigned Numbers Authority',
        'AS14061 Digitalocean LLC',
      ],
    },
    {
      'ipaddress': '104.238.173.18',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'GB',
      'stateprov': 'England',
      'district': 'Greater London',
      'city': 'London',
      'zipcode': 'E1 6QR',
      'location': '51.5204,-0.0737773',
      'latitude': 51.5204,
      'longitude': -0.0737773,
      'timezone_offset': 0,
      'timezone_name': 'Europe/London',
      'ispname': 'Choopa',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Choopa LLC',
        'Choopa LLC',
        'AS20473 Choopa LLC',
      ],
    },
    {
      'ipaddress': '107.170.20.33',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 4,
      'blacklist_observations': 110,
      'country': 'US',
      'stateprov': 'New York',
      'district': 'New York',
      'city': 'New York',
      'zipcode': '10011',
      'location': '40.7465,-74.0094',
      'latitude': 40.7465,
      'longitude': -74.0094,
      'timezone_offset': -5,
      'timezone_name': 'America/New_York',
      'ispname': 'DigitalOcean, LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Digital Ocean, Inc.',
        'Digital Ocean, Inc.',
        'AS14061 Digitalocean LLC',
      ],
    },
    {
      'ipaddress': '107.181.174.34',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'US',
      'stateprov': 'California',
      'district': 'Los Angeles',
      'city': 'Los Angeles (Downtown)',
      'zipcode': '90014',
      'location': '34.0484,-118.255',
      'latitude': 34.0484,
      'longitude': -118.255,
      'timezone_offset': -8,
      'timezone_name': 'America/Los_Angeles',
      'ispname': 'Total Server Solutions L.L.C.',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Total Server Solutions L.L.C.',
        'AS204957 LAYER6',
      ],
    },
    {
      'ipaddress': '107.181.187.228',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'US',
      'stateprov': 'California',
      'district': 'Los Angeles',
      'city': 'Los Angeles (Downtown)',
      'zipcode': '90014',
      'location': '34.0484,-118.255',
      'latitude': 34.0484,
      'longitude': -118.255,
      'timezone_offset': -8,
      'timezone_name': 'America/Los_Angeles',
      'ispname': 'Total Server Solutions L.L.C.',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS46562 Total Server Solutions L L C',
      ],
    },
    {
      'ipaddress': '109.234.35.123',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Sverdlovsk',
      'district': 'gorod Pervouralsk',
      'city': 'Pervouralsk (Zavodoupravleniye Korpus 2)',
      'zipcode': '',
      'location': '56.8976,59.9741',
      'latitude': 56.8976,
      'longitude': 59.9741,
      'timezone_offset': 5,
      'timezone_name': 'Asia/Yekaterinburg',
      'ispname': 'VDSINA',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Webzilla B.V.',
        'AS48282 MCHOST AS',
      ],
    },
    {
      'ipaddress': '109.234.35.128',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Sverdlovsk',
      'district': 'gorod Pervouralsk',
      'city': 'Pervouralsk (Zavodoupravleniye Korpus 2)',
      'zipcode': '',
      'location': '56.8976,59.9741',
      'latitude': 56.8976,
      'longitude': 59.9741,
      'timezone_offset': 5,
      'timezone_name': 'Asia/Yekaterinburg',
      'ispname': 'VDSINA',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Webzilla B.V.',
        'Webzilla B.V.',
        'Webzilla B.V.',
        'Webzilla B.V.',
        'Webzilla B.V.',
        'Webzilla B.V.',
        'AS48282 MCHOST AS',
      ],
    },
    {
      'ipaddress': '109.234.35.75',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Sverdlovsk',
      'district': 'gorod Pervouralsk',
      'city': 'Pervouralsk (Zavodoupravleniye Korpus 2)',
      'zipcode': '',
      'location': '56.8976,59.9741',
      'latitude': 56.8976,
      'longitude': 59.9741,
      'timezone_offset': 5,
      'timezone_name': 'Asia/Yekaterinburg',
      'ispname': 'VDSINA',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS48282 MCHOST AS',
      ],
    },
    {
      'ipaddress': '109.237.111.168',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Novosibirsk',
      'district': 'Novosibirskiy Rayon',
      'city': 'Novosibirsk',
      'zipcode': '',
      'location': '54.988,82.913',
      'latitude': 54.988,
      'longitude': 82.913,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Novosibirsk',
      'ispname': 'ADMAN',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Krek Ltd.',
        'Krek Ltd.',
        'AS57494 ADMAN AS',
      ],
    },
    {
      'ipaddress': '109.248.222.47',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Novosibirsk',
      'district': 'Novosibirskiy Rayon',
      'city': 'Novosibirsk',
      'zipcode': '',
      'location': '54.9879,82.913',
      'latitude': 54.9879,
      'longitude': 82.913,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Novosibirsk',
      'ispname': 'ADMAN',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS57494 ADMAN AS',
      ],
    },
    {
      'ipaddress': '109.248.222.50',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Novosibirsk',
      'district': 'Novosibirskiy Rayon',
      'city': 'Novosibirsk',
      'zipcode': '',
      'location': '54.9879,82.913',
      'latitude': 54.9879,
      'longitude': 82.913,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Novosibirsk',
      'ispname': 'ADMAN',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS57494 ADMAN AS',
      ],
    },
    {
      'ipaddress': '138.201.118.102',
      'threat_potential_score_pct': 83.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'DE',
      'stateprov': 'Bavaria',
      'district': 'Upper Palatinate',
      'city': 'Falkenstein',
      'zipcode': '93167',
      'location': '49.0976,12.4869',
      'latitude': 49.0976,
      'longitude': 12.4869,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Berlin',
      'ispname': 'Hetzner',
      'network_type': [
        'Worldwide Networks',
        'Search Engine Networks',
      ],
      'network_group': [
        'All ASN Networks',
        'Search Engine Services',
      ],
      'network_name': [
        'Hetzner Online GmbH',
        'Hetzner Online GmbH',
        'AS24940 HETZNER AS',
        'HETZNER AS',
      ],
    },
    {
      'ipaddress': '138.201.93.46',
      'threat_potential_score_pct': 83.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'DE',
      'stateprov': 'Bavaria',
      'district': 'Upper Palatinate',
      'city': 'Falkenstein',
      'zipcode': '93167',
      'location': '49.0976,12.4869',
      'latitude': 49.0976,
      'longitude': 12.4869,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Berlin',
      'ispname': 'Hetzner',
      'network_type': [
        'Worldwide Networks',
        'Search Engine Networks',
      ],
      'network_group': [
        'All ASN Networks',
        'Search Engine Services',
      ],
      'network_name': [
        'Hetzner Online GmbH',
        'AS24940 HETZNER AS',
        'HETZNER AS',
      ],
    },
    {
      'ipaddress': '138.201.95.72',
      'threat_potential_score_pct': 83.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'DE',
      'stateprov': 'Bavaria',
      'district': 'Upper Palatinate',
      'city': 'Falkenstein',
      'zipcode': '93167',
      'location': '49.0976,12.4869',
      'latitude': 49.0976,
      'longitude': 12.4869,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Berlin',
      'ispname': 'Hetzner',
      'network_type': [
        'Worldwide Networks',
        'Search Engine Networks',
      ],
      'network_group': [
        'All ASN Networks',
        'Search Engine Services',
      ],
      'network_name': [
        'Hetzner Online GmbH',
        'AS24940 HETZNER AS',
        'HETZNER AS',
      ],
    },
    {
      'ipaddress': '139.59.147.0',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'DE',
      'stateprov': 'Hesse',
      'district': 'Regierungsbezirk Darmstadt',
      'city': 'Frankfurt am Main',
      'zipcode': '60313',
      'location': '50.1109,8.68213',
      'latitude': 50.1109,
      'longitude': 8.68213,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Berlin',
      'ispname': 'DigitalOcean, LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        null,
        'AS14061 Digitalocean LLC',
      ],
    },
    {
      'ipaddress': '141.8.226.58',
      'threat_potential_score_pct': 73.8,
      'threat_classification': 'High',
      'blacklist_class': 'zeus',
      'blacklist_class_cnt': 4,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 264,
      'country': 'CH',
      'stateprov': 'Zurich',
      'district': 'Bezirk Horgen',
      'city': 'Thalwil',
      'zipcode': '8800',
      'location': '47.2839,8.56491',
      'latitude': 47.2839,
      'longitude': 8.56491,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Zurich',
      'ispname': 'ROOKMEDIA',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS40034 Confluence Networks Inc',
      ],
    },
    {
      'ipaddress': '146.120.110.46',
      'threat_potential_score_pct': 88.8,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Moscow',
      'district': 'Moscow',
      'city': 'Moscow',
      'zipcode': '',
      'location': '55.7558,37.6173',
      'latitude': 55.7558,
      'longitude': 37.6173,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'RECONN. Operator Svyazi, LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS44546 ALFATELECOM',
      ],
    },
    {
      'ipaddress': '146.185.137.40',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'NL',
      'stateprov': 'North Holland',
      'district': 'Gemeente Amsterdam',
      'city': 'Amsterdam-Zuidoost',
      'zipcode': '1105',
      'location': '52.2959,4.94417',
      'latitude': 52.2959,
      'longitude': 4.94417,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Amsterdam',
      'ispname': 'DigitalOcean, LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'AS14061 Digitalocean LLC',
      ],
    },
    {
      'ipaddress': '146.185.155.126',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'NL',
      'stateprov': 'North Holland',
      'district': 'Gemeente Amsterdam',
      'city': 'Amsterdam-Zuidoost',
      'zipcode': '1105',
      'location': '52.2959,4.94417',
      'latitude': 52.2959,
      'longitude': 4.94417,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Amsterdam',
      'ispname': 'DigitalOcean, LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Internet Assigned Numbers Authority',
        'AS14061 Digitalocean LLC',
      ],
    },
    {
      'ipaddress': '146.185.249.189',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'St.-Petersburg',
      'district': 'gorod Sankt-Peterburg',
      'city': 'St Petersburg',
      'zipcode': '',
      'location': '59.9343,30.3351',
      'latitude': 59.9343,
      'longitude': 30.3351,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'VMAGE LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Petersburg Internet Network ltd.',
        'AS44676 VMAGE AS',
      ],
    },
    {
      'ipaddress': '148.163.73.29',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'US',
      'stateprov': 'Delaware',
      'district': 'Sussex',
      'city': 'Lewes',
      'zipcode': '19958',
      'location': '38.7651,-75.2116',
      'latitude': 38.7651,
      'longitude': -75.2116,
      'timezone_offset': -5,
      'timezone_name': 'America/New_York',
      'ispname': 'Input Output Flood LLC',
      'network_type': [],
      'network_group': [],
      'network_name': [
        'Input Output Flood LLC',
      ],
    },
    {
      'ipaddress': '149.154.152.108',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'AT',
      'stateprov': 'Styria',
      'district': 'Graz Stadt',
      'city': 'Graz (Innere Stadt)',
      'zipcode': '8010',
      'location': '47.0705,15.4379',
      'latitude': 47.0705,
      'longitude': 15.4379,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Vienna',
      'ispname': 'EDIS GmbH',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'EDIS GmbH',
        'AS57169 EDIS AS EU',
      ],
    },
    {
      'ipaddress': '149.154.157.14',
      'threat_potential_score_pct': 91.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'IT',
      'stateprov': 'Lombardy',
      'district': 'Milan',
      'city': 'Milan',
      'zipcode': '20121',
      'location': '45.4584,9.16247',
      'latitude': 45.4584,
      'longitude': 9.16247,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Rome',
      'ispname': 'ONE ON CDLAN SRL',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'CDLAN s.r.l.',
        'CDLAN s.r.l.',
        'AS20836 CDLAN AS Milano',
      ],
    },
    {
      'ipaddress': '149.154.159.179',
      'threat_potential_score_pct': 83.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'DE',
      'stateprov': 'Hesse',
      'district': 'Regierungsbezirk Darmstadt',
      'city': 'Frankfurt am Main (Ostend)',
      'zipcode': '60386',
      'location': '50.12,8.73527',
      'latitude': 50.12,
      'longitude': 8.73527,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Berlin',
      'ispname': 'EDIS',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'velia.net Internetdienste GmbH',
        'AS47447 TTM',
      ],
    },
    {
      'ipaddress': '149.154.68.190',
      'threat_potential_score_pct': 83.8,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Irkutsk',
      'district': 'Irkutskiy Rayon',
      'city': 'Irkutsk',
      'zipcode': '',
      'location': '52.287,104.305',
      'latitude': 52.287,
      'longitude': 104.305,
      'timezone_offset': 8,
      'timezone_name': 'Asia/Irkutsk',
      'ispname': 'TheFirst',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS29182 ISPSYSTEM AS',
      ],
    },
    {
      'ipaddress': '149.202.109.202',
      'threat_potential_score_pct': 86,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'FR',
      'stateprov': 'Auvergne-RhÃ´ne-Alpes',
      'district': 'IsÃ¨re',
      'city': 'Beaulieu',
      'zipcode': '38470',
      'location': '45.1938,5.39231',
      'latitude': 45.1938,
      'longitude': 5.39231,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Paris',
      'ispname': 'OVH',
      'network_type': [
        'Worldwide Networks',
        'File Sharing Networks',
      ],
      'network_group': [
        'All ASN Networks',
        'File Sharing Service',
      ],
      'network_name': [
        'OVH SAS',
        'AS16276 OVH',
        'OVH',
      ],
    },
    {
      'ipaddress': '149.202.52.215',
      'threat_potential_score_pct': 86,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'FR',
      'stateprov': 'Grand Est',
      'district': 'Bas-Rhin',
      'city': 'Strasbourg',
      'zipcode': '67000',
      'location': '48.5734,7.75211',
      'latitude': 48.5734,
      'longitude': 7.75211,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Paris',
      'ispname': 'OVH SAS',
      'network_type': [
        'Worldwide Networks',
        'File Sharing Networks',
      ],
      'network_group': [
        'All ASN Networks',
        'File Sharing Service',
      ],
      'network_name': [
        'AS16276 OVH',
        'OVH',
      ],
    },
    {
      'ipaddress': '151.236.14.51',
      'threat_potential_score_pct': 82.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'NL',
      'stateprov': 'North Holland',
      'district': 'Gemeente Amsterdam',
      'city': 'Amsterdam',
      'zipcode': '1012',
      'location': '52.3702,4.89517',
      'latitude': 52.3702,
      'longitude': 4.89517,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Amsterdam',
      'ispname': 'EDIS',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'NFOrce Entertainment BV',
        'AS43350 NFORCE',
      ],
    },
    {
      'ipaddress': '151.236.15.226',
      'threat_potential_score_pct': 83.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'DE',
      'stateprov': 'Hesse',
      'district': 'Regierungsbezirk Darmstadt',
      'city': 'Frankfurt am Main (Ostend)',
      'zipcode': '60386',
      'location': '50.12,8.73527',
      'latitude': 50.12,
      'longitude': 8.73527,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Berlin',
      'ispname': 'velia.net',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'velia.net Internetdienste GmbH',
        'AS47447 TTM',
      ],
    },
    {
      'ipaddress': '158.255.6.109',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 4,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Moscow',
      'district': 'Central Administrative Okrug',
      'city': 'Moscow',
      'zipcode': '',
      'location': '55.7336,37.5852',
      'latitude': 55.7336,
      'longitude': 37.5852,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'hostkey network',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Mir Telematiki Ltd.',
        'AS49335 NCONNECT AS',
      ],
    },
    {
      'ipaddress': '158.255.6.115',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 4,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Moscow',
      'district': 'Central Administrative Okrug',
      'city': 'Moscow',
      'zipcode': '',
      'location': '55.7336,37.5852',
      'latitude': 55.7336,
      'longitude': 37.5852,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'hostkey network',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Mir Telematiki Ltd.',
        'AS49335 NCONNECT AS',
      ],
    },
    {
      'ipaddress': '158.69.223.5',
      'threat_potential_score_pct': 86,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'CA',
      'stateprov': 'Quebec',
      'district': 'MontÃ©rÃ©gie',
      'city': 'Beauharnois',
      'zipcode': 'J6N',
      'location': '45.3151,-73.8779',
      'latitude': 45.3151,
      'longitude': -73.8779,
      'timezone_offset': -5,
      'timezone_name': 'America/Toronto',
      'ispname': 'OVH Hosting',
      'network_type': [
        'Worldwide Networks',
        'Content Delivery Networks',
        'File Sharing Networks',
      ],
      'network_group': [
        'All ASN Networks',
        'Commercial CDN',
        'File Sharing Service',
      ],
      'network_name': [
        'OVH SAS',
        'AS16276 OVH',
        'OVH',
        'OVH',
      ],
    },
    {
      'ipaddress': '164.132.40.47',
      'threat_potential_score_pct': 86,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'FR',
      'stateprov': 'Hauts-de-France',
      'district': 'North',
      'city': 'Gravelines',
      'zipcode': '59820',
      'location': '50.9871,2.12554',
      'latitude': 50.9871,
      'longitude': 2.12554,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Paris',
      'ispname': 'OVH SAS',
      'network_type': [
        'Worldwide Networks',
        'File Sharing Networks',
      ],
      'network_group': [
        'All ASN Networks',
        'File Sharing Service',
      ],
      'network_name': [
        'OVH SAS',
        'AS16276 OVH',
        'OVH',
      ],
    },
    {
      'ipaddress': '176.107.185.19',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Kyiv City',
      'district': 'Kyiv',
      'city': 'Kyiv',
      'zipcode': '',
      'location': '50.4501,30.5234',
      'latitude': 50.4501,
      'longitude': 30.5234,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'DELTAHOST',
      'network_type': [],
      'network_group': [],
      'network_name': [],
    },
    {
      'ipaddress': '176.114.3.173',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': "Kyivs'ka Oblast",
      'district': "Kyjevo-Svyatoshyns'kyi district",
      'city': 'Boiarka',
      'zipcode': '',
      'location': '50.323,30.2964',
      'latitude': 50.323,
      'longitude': 30.2964,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Hosting Provider TheHost',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS56485 THEHOST AS',
      ],
    },
    {
      'ipaddress': '176.121.14.95',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'BZ',
      'stateprov': 'Belize',
      'district': '',
      'city': 'Belize City',
      'zipcode': '',
      'location': '17.5046,-88.1962',
      'latitude': 17.5046,
      'longitude': -88.1962,
      'timezone_offset': -6,
      'timezone_name': 'America/Belize',
      'ispname': 'Cognifide Polska Sp. z o.o.',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'SBA Dubrovskiy',
        'SBA Dubrovskiy',
        'AS210138 FLOWSPEC AS',
      ],
    },
    {
      'ipaddress': '176.31.127.168',
      'threat_potential_score_pct': 86,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'FR',
      'stateprov': 'Hauts-de-France',
      'district': 'North',
      'city': 'Roubaix',
      'zipcode': '59100',
      'location': '50.6916,3.20158',
      'latitude': 50.6916,
      'longitude': 3.20158,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Paris',
      'ispname': 'OVH ISP',
      'network_type': [
        'Worldwide Networks',
        'File Sharing Networks',
      ],
      'network_group': [
        'All ASN Networks',
        'File Sharing Service',
      ],
      'network_name': [
        'AS16276 OVH',
        'OVH',
      ],
    },
    {
      'ipaddress': '176.31.47.100',
      'threat_potential_score_pct': 86,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'DE',
      'stateprov': 'Berlin',
      'district': '',
      'city': 'Berlin',
      'zipcode': '10178',
      'location': '52.5192,13.4061',
      'latitude': 52.5192,
      'longitude': 13.4061,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Berlin',
      'ispname': 'OVH SAS',
      'network_type': [
        'Worldwide Networks',
        'File Sharing Networks',
      ],
      'network_group': [
        'All ASN Networks',
        'File Sharing Service',
      ],
      'network_name': [
        'OVH SAS',
        'AS16276 OVH',
        'OVH',
      ],
    },
    {
      'ipaddress': '176.53.21.105',
      'threat_potential_score_pct': 91.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'TR',
      'stateprov': 'Istanbul',
      'district': 'SarÄ±yer',
      'city': 'Istanbul',
      'zipcode': '34122',
      'location': '41.1116,29.0268',
      'latitude': 41.1116,
      'longitude': 29.0268,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Istanbul',
      'ispname': 'Istanbuldc Veri Merkezi Ltd. Sti',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Internet Assigned Numbers Authority',
        'AS197328 INETLTD',
      ],
    },
    {
      'ipaddress': '176.9.172.166',
      'threat_potential_score_pct': 83.8,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'DE',
      'stateprov': 'Bavaria',
      'district': 'Upper Palatinate',
      'city': 'Falkenstein',
      'zipcode': '93167',
      'location': '49.0976,12.4869',
      'latitude': 49.0976,
      'longitude': 12.4869,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Berlin',
      'ispname': 'Hetzner',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS24940 HETZNER AS',
      ],
    },
    {
      'ipaddress': '178.62.232.244',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'NL',
      'stateprov': 'North Holland',
      'district': 'Gemeente Amsterdam',
      'city': 'Amsterdam',
      'zipcode': '1098',
      'location': '52.3563,4.95714',
      'latitude': 52.3563,
      'longitude': 4.95714,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Amsterdam',
      'ispname': 'DigitalOcean, LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Internet Assigned Numbers Authority',
        'AS14061 Digitalocean LLC',
      ],
    },
    {
      'ipaddress': '178.63.238.185',
      'threat_potential_score_pct': 83.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'DE',
      'stateprov': 'Bavaria',
      'district': 'Middle Franconia',
      'city': 'Gunzenhausen (Frickenfelden)',
      'zipcode': '91710',
      'location': '49.1247,10.7806',
      'latitude': 49.1247,
      'longitude': 10.7806,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Berlin',
      'ispname': 'Hetzner',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Hetzner Online GmbH',
        'Hetzner Online GmbH',
        'AS24940 HETZNER AS',
      ],
    },
    {
      'ipaddress': '185.100.85.150',
      'threat_potential_score_pct': 89,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 11,
      'blacklist_observations': 110,
      'country': 'RO',
      'stateprov': 'BucureÅŸti',
      'district': 'Municipiul BucureÅŸti',
      'city': 'Bucharest',
      'zipcode': '',
      'location': '44.4325,26.1039',
      'latitude': 44.4325,
      'longitude': 26.1039,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Bucharest',
      'ispname': 'FlokiNET ehf',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'AS200651 FLOKINET',
      ],
    },
    {
      'ipaddress': '185.102.136.67',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Moscow',
      'district': 'Moscow',
      'city': 'Moscow',
      'zipcode': '',
      'location': '55.7558,37.6173',
      'latitude': 55.7558,
      'longitude': 37.6173,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'Reg.Ru AG',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Rices Privately owned enterprise',
        'AS202423 MGNHOST AS',
      ],
    },
    {
      'ipaddress': '185.102.136.77',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Moscow',
      'district': 'Moscow',
      'city': 'Moscow',
      'zipcode': '',
      'location': '55.7558,37.6173',
      'latitude': 55.7558,
      'longitude': 37.6173,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'Reg.Ru AG',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Rices Privately owned enterprise',
        'AS202423 MGNHOST AS',
      ],
    },
    {
      'ipaddress': '185.106.122.38',
      'threat_potential_score_pct': 86,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'RO',
      'stateprov': 'BucureÅŸti',
      'district': 'Municipiul BucureÅŸti',
      'city': 'Bucharest',
      'zipcode': '',
      'location': '44.4325,26.1039',
      'latitude': 44.4325,
      'longitude': 26.1039,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Bucharest',
      'ispname': 'EU-HOSTSAILOR',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Host Sailor Ltd.',
        'AS60117 HS',
      ],
    },
    {
      'ipaddress': '185.115.140.170',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Moscow Oblast',
      'district': 'Krasnogorskiy Rayon',
      'city': 'Putilkovo',
      'zipcode': '',
      'location': '55.8636,37.3908',
      'latitude': 55.8636,
      'longitude': 37.3908,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'MEGASERVER network in eServer.ru',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS42244 ESERVER',
      ],
    },
    {
      'ipaddress': '185.117.153.176',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Moscow',
      'district': 'Severnyy Administrativnyy Okrug',
      'city': 'Moscow',
      'zipcode': '',
      'location': '55.8134,37.5314',
      'latitude': 55.8134,
      'longitude': 37.5314,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'MAROSNET Telecommunication Company Network',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'MAROSNET Telecommunication Company LLC',
        'AS48666 Moscow Russia',
      ],
    },
  ],
},
{
  'queryName': 'Sample watchlist - Ransomware 2',
  'description': '50 IPs',
  'createdOn': new Date(),
  'userEmail': userEmail,
  'ips': [
    {
      'ipaddress': '91.219.29.81',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 11,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Kharkiv',
      'district': "Kharkivs'ka city council",
      'city': "Kharkiv (Dzerzhyns'kyi District)",
      'zipcode': '',
      'location': '50.0069,36.221',
      'latitude': 50.0069,
      'longitude': 36.221,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'LuckyNet Datacenter',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Lucky Net Ltd',
        'AS3254 Lucky Net Ltd',
      ],
    },
    {
      'ipaddress': '91.219.30.254',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Kharkiv',
      'district': "Kharkivs'ka city council",
      'city': "Kharkiv (Dzerzhyns'kyi District)",
      'zipcode': '',
      'location': '50.0069,36.221',
      'latitude': 50.0069,
      'longitude': 36.221,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'LuckyNet Datacenter',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Lucky Net Ltd',
        'AS3254 Lucky Net Ltd',
      ],
    },
    {
      'ipaddress': '91.219.31.14',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Kharkiv',
      'district': "Kharkivs'ka city council",
      'city': "Kharkiv (Dzerzhyns'kyi District)",
      'zipcode': '',
      'location': '50.0069,36.221',
      'latitude': 50.0069,
      'longitude': 36.221,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Selectel',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'AS50340 SELECTEL MSK',
      ],
    },
    {
      'ipaddress': '91.219.31.15',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Kharkiv',
      'district': "Kharkivs'ka city council",
      'city': "Kharkiv (Dzerzhyns'kyi District)",
      'zipcode': '',
      'location': '50.0069,36.221',
      'latitude': 50.0069,
      'longitude': 36.221,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Selectel',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Internet Assigned Numbers Authority',
        'AS50340 SELECTEL MSK',
      ],
    },
    {
      'ipaddress': '91.219.31.18',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Kharkiv',
      'district': "Kharkivs'ka city council",
      'city': "Kharkiv (Dzerzhyns'kyi District)",
      'zipcode': '',
      'location': '50.0069,36.221',
      'latitude': 50.0069,
      'longitude': 36.221,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Selectel',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Internet Assigned Numbers Authority',
        'AS50340 SELECTEL MSK',
      ],
    },
    {
      'ipaddress': '91.223.180.240',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': "Kyivs'ka Oblast",
      'district': "Kyjevo-Svyatoshyns'kyi district",
      'city': 'Boiarka',
      'zipcode': '',
      'location': '50.323,30.2964',
      'latitude': 50.323,
      'longitude': 30.2964,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Hosting Provider TheHost',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'FOP Sedinkin Olexandr Valeriyovuch',
        'AS56485 THEHOST AS',
      ],
    },
    {
      'ipaddress': '91.223.88.205',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Donetsk',
      'district': 'Donetsâ€™ka Misâ€™krada',
      'city': 'Donetsk (Kyivskyi District)',
      'zipcode': '',
      'location': '48.0597,37.7722',
      'latitude': 48.0597,
      'longitude': 37.7722,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Private Person Anton Malyi',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Private Person Anton Malyi',
        'AS44803 CONTUROV AS',
      ],
    },
    {
      'ipaddress': '91.223.88.50',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Donetsk',
      'district': 'Donetsâ€™ka Misâ€™krada',
      'city': 'Donetsk (Kyivskyi District)',
      'zipcode': '',
      'location': '48.0597,37.7722',
      'latitude': 48.0597,
      'longitude': 37.7722,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Private Person Anton Malyi',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS44803 CONTUROV AS',
      ],
    },
    {
      'ipaddress': '91.226.92.202',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Altay Kray',
      'district': '',
      'city': 'Altay Kray',
      'zipcode': '',
      'location': '52.1665,81.36',
      'latitude': 52.1665,
      'longitude': 81.36,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Barnaul',
      'ispname': 'PJSC Rostelecom',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'PJSC Rostelecom',
        'AS12389 ROSTELECOM AS',
      ],
    },
    {
      'ipaddress': '91.226.92.204',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Altay Kray',
      'district': '',
      'city': 'Altay Kray',
      'zipcode': '',
      'location': '52.1665,81.36',
      'latitude': 52.1665,
      'longitude': 81.36,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Barnaul',
      'ispname': 'PJSC Rostelecom',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'PJSC Rostelecom',
        'AS12389 ROSTELECOM AS',
      ],
    },
    {
      'ipaddress': '91.226.92.208',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Altay Kray',
      'district': '',
      'city': 'Altay Kray',
      'zipcode': '',
      'location': '52.1665,81.36',
      'latitude': 52.1665,
      'longitude': 81.36,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Barnaul',
      'ispname': 'PJSC Rostelecom',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'PJSC Rostelecom',
        'PJSC Rostelecom',
        'AS12389 ROSTELECOM AS',
      ],
    },
    {
      'ipaddress': '91.226.93.113',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Altay Kray',
      'district': '',
      'city': 'Altay Kray',
      'zipcode': '',
      'location': '52.1665,81.36',
      'latitude': 52.1665,
      'longitude': 81.36,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Barnaul',
      'ispname': 'PJSC Rostelecom',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'PJSC Rostelecom',
        'AS12389 ROSTELECOM AS',
      ],
    },
    {
      'ipaddress': '91.226.93.124',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Altay Kray',
      'district': '',
      'city': 'Altay Kray',
      'zipcode': '',
      'location': '52.1665,81.36',
      'latitude': 52.1665,
      'longitude': 81.36,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Barnaul',
      'ispname': 'PJSC Rostelecom',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'PJSC Rostelecom',
        'AS12389 ROSTELECOM AS',
      ],
    },
    {
      'ipaddress': '91.228.239.216',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Moscow',
      'district': 'Yugo-Zapadny Administrative Okrug',
      'city': 'Moscow',
      'zipcode': '',
      'location': '55.6526,37.5289',
      'latitude': 55.6526,
      'longitude': 37.5289,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'MixTelecom',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS57487 MIXTELECOM AS',
      ],
    },
    {
      'ipaddress': '91.229.188.178',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Moscow',
      'district': 'Moscow',
      'city': 'Moscow',
      'zipcode': '',
      'location': '55.7558,37.6173',
      'latitude': 55.7558,
      'longitude': 37.6173,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'Seven Network Inc',
      'network_type': [],
      'network_group': [],
      'network_name': [],
    },
    {
      'ipaddress': '91.230.211.103',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Krasnoyarskiy',
      'district': 'gorod Krasnoyarsk',
      'city': 'Krasnoyarsk',
      'zipcode': '',
      'location': '56.0263,92.9052',
      'latitude': 56.0263,
      'longitude': 92.9052,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Krasnoyarsk',
      'ispname': 'Optibit LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Optizon Ltd',
        'Optizon Ltd',
        'AS8496 RU OPTIBIT',
      ],
    },
    {
      'ipaddress': '91.230.211.139',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Krasnoyarskiy',
      'district': 'gorod Krasnoyarsk',
      'city': 'Krasnoyarsk',
      'zipcode': '',
      'location': '56.0263,92.9052',
      'latitude': 56.0263,
      'longitude': 92.9052,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Krasnoyarsk',
      'ispname': 'Optibit LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Optizon Ltd',
        'Optizon Ltd',
        'AS8496 RU OPTIBIT',
      ],
    },
    {
      'ipaddress': '91.230.211.187',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Krasnoyarskiy',
      'district': 'gorod Krasnoyarsk',
      'city': 'Krasnoyarsk',
      'zipcode': '',
      'location': '56.0263,92.9052',
      'latitude': 56.0263,
      'longitude': 92.9052,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Krasnoyarsk',
      'ispname': 'Optibit LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Optizon Ltd',
        'Optizon Ltd',
        'AS8496 RU OPTIBIT',
      ],
    },
    {
      'ipaddress': '91.230.211.26',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Krasnoyarskiy',
      'district': 'gorod Krasnoyarsk',
      'city': 'Krasnoyarsk',
      'zipcode': '',
      'location': '56.0263,92.9052',
      'latitude': 56.0263,
      'longitude': 92.9052,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Krasnoyarsk',
      'ispname': 'Optibit LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Optizon Ltd',
        'Optizon Ltd',
        'Optizon Ltd',
        'Optizon Ltd',
        'AS8496 RU OPTIBIT',
      ],
    },
    {
      'ipaddress': '91.234.32.192',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': "Kyivs'ka Oblast",
      'district': "Kyjevo-Svyatoshyns'kyi district",
      'city': 'Boiarka',
      'zipcode': '',
      'location': '50.323,30.2964',
      'latitude': 50.323,
      'longitude': 30.2964,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Hosting Provider TheHost',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'FOP Sedinkin Olexandr Valeriyovuch',
        'AS56485 THEHOST AS',
      ],
    },
    {
      'ipaddress': '91.234.33.149',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 4,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': "Kyivs'ka Oblast",
      'district': "Kyjevo-Svyatoshyns'kyi district",
      'city': 'Boiarka',
      'zipcode': '',
      'location': '50.323,30.2964',
      'latitude': 50.323,
      'longitude': 30.2964,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Hosting Provider TheHost',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'FOP Sedinkin Olexandr Valeriyovuch',
        'AS56485 THEHOST AS',
      ],
    },
    {
      'ipaddress': '91.234.33.215',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 4,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': "Kyivs'ka Oblast",
      'district': "Kyjevo-Svyatoshyns'kyi district",
      'city': 'Boiarka',
      'zipcode': '',
      'location': '50.323,30.2964',
      'latitude': 50.323,
      'longitude': 30.2964,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Hosting Provider TheHost',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'FOP Sedinkin Olexandr Valeriyovuch',
        'AS56485 THEHOST AS',
      ],
    },
    {
      'ipaddress': '91.234.34.98',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': "Kyivs'ka Oblast",
      'district': "Kyjevo-Svyatoshyns'kyi district",
      'city': 'Boiarka',
      'zipcode': '',
      'location': '50.323,30.2964',
      'latitude': 50.323,
      'longitude': 30.2964,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Hosting Provider TheHost',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'FOP Sedinkin Olexandr Valeriyovuch',
        'AS56485 THEHOST AS',
      ],
    },
    {
      'ipaddress': '91.234.35.216',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': "Kyivs'ka Oblast",
      'district': "Kyjevo-Svyatoshyns'kyi district",
      'city': 'Boiarka',
      'zipcode': '',
      'location': '50.323,30.2964',
      'latitude': 50.323,
      'longitude': 30.2964,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Hosting Provider TheHost',
      'network_type': [],
      'network_group': [],
      'network_name': [
        'FOP Sedinkin Olexandr Valeriyovuch',
      ],
    },
    {
      'ipaddress': '91.234.35.243',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': "Kyivs'ka Oblast",
      'district': "Kyjevo-Svyatoshyns'kyi district",
      'city': 'Boiarka',
      'zipcode': '',
      'location': '50.323,30.2964',
      'latitude': 50.323,
      'longitude': 30.2964,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Hosting Provider TheHost',
      'network_type': [],
      'network_group': [],
      'network_name': [
        'FOP Sedinkin Olexandr Valeriyovuch',
      ],
    },
    {
      'ipaddress': '91.237.247.24',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Rivne',
      'district': '',
      'city': 'Rivne',
      'zipcode': '',
      'location': '50.6236,26.2651',
      'latitude': 50.6236,
      'longitude': 26.2651,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Campus Networks',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'PE Pashinska Oksana Vasulivna',
        'AS50392 CAMPUS RV AS',
      ],
    },
    {
      'ipaddress': '91.239.235.130',
      'threat_potential_score_pct': 94.6,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Kyiv City',
      'district': 'Kyiv City',
      'city': "Kyiv (Podil's'kyi district)",
      'zipcode': '',
      'location': '50.4703,30.5077',
      'latitude': 50.4703,
      'longitude': 30.5077,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': 'Hostpro Ltd.',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'Internet Assigned Numbers Authority',
        'AS196645 HOSTPRO AS',
      ],
    },
    {
      'ipaddress': '91.247.37.137',
      'threat_potential_score_pct': 91.8,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'BG',
      'stateprov': 'Burgas',
      'district': 'Obshtina Burgas',
      'city': 'Burgas',
      'zipcode': '8000',
      'location': '42.5188,27.4773',
      'latitude': 42.5188,
      'longitude': 27.4773,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Sofia',
      'ispname': 'ITL Company',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS59729 ITL',
      ],
    },
    {
      'ipaddress': '92.222.71.26',
      'threat_potential_score_pct': 86,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'BE',
      'stateprov': 'Brussels Capital',
      'district': 'Bruxelles-Capitale',
      'city': 'Brussels',
      'zipcode': '1000',
      'location': '50.8503,4.35171',
      'latitude': 50.8503,
      'longitude': 4.35171,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Brussels',
      'ispname': 'OVH SAS',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'OVH SAS',
        'OVH SAS',
        'AS16276 OVH',
      ],
    },
    {
      'ipaddress': '92.63.87.106',
      'threat_potential_score_pct': 89,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'LV',
      'stateprov': 'Riga',
      'district': 'RÄ«ga',
      'city': 'Riga (Zemgales priekÅ¡pilsÄ“ta)',
      'zipcode': '',
      'location': '56.9498,24.066',
      'latitude': 56.9498,
      'longitude': 24.066,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Riga',
      'ispname': 'IT_SERVICES',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'SIA MWTV',
        'SIA MWTV',
        'AS15615 IT SERVICES',
      ],
    },
    {
      'ipaddress': '92.63.87.134',
      'threat_potential_score_pct': 89,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'LV',
      'stateprov': 'Riga',
      'district': 'RÄ«ga',
      'city': 'Riga (Zemgales priekÅ¡pilsÄ“ta)',
      'zipcode': '',
      'location': '56.9498,24.066',
      'latitude': 56.9498,
      'longitude': 24.066,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Riga',
      'ispname': 'IT_SERVICES',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'SIA MWTV',
        'AS15615 IT SERVICES',
      ],
    },
    {
      'ipaddress': '92.63.87.48',
      'threat_potential_score_pct': 89,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'LV',
      'stateprov': 'Riga',
      'district': 'RÄ«ga',
      'city': 'Riga (Zemgales priekÅ¡pilsÄ“ta)',
      'zipcode': '',
      'location': '56.9498,24.066',
      'latitude': 56.9498,
      'longitude': 24.066,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Riga',
      'ispname': 'IT_SERVICES',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'SIA MWTV',
        'AS15615 IT SERVICES',
      ],
    },
    {
      'ipaddress': '92.63.87.53',
      'threat_potential_score_pct': 89,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'LV',
      'stateprov': 'Riga',
      'district': 'RÄ«ga',
      'city': 'Riga (Zemgales priekÅ¡pilsÄ“ta)',
      'zipcode': '',
      'location': '56.9498,24.066',
      'latitude': 56.9498,
      'longitude': 24.066,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Riga',
      'ispname': 'IT_SERVICES',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'SIA MWTV',
        'AS15615 IT SERVICES',
      ],
    },
    {
      'ipaddress': '93.170.104.127',
      'threat_potential_score_pct': 88.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'NL',
      'stateprov': 'North Holland',
      'district': 'Gemeente Amsterdam',
      'city': 'Amsterdam',
      'zipcode': '1012',
      'location': '52.3702,4.89517',
      'latitude': 52.3702,
      'longitude': 4.89517,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Amsterdam',
      'ispname': "Seflow S.N.C. Di Marco Brame' & C.",
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'ALFA TELECOM s.r.o.',
        'Serverel Corp.',
        'AS44546 ALFATELECOM',
      ],
    },
    {
      'ipaddress': '93.170.123.119',
      'threat_potential_score_pct': 88.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 7,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Lviv',
      'district': "L'vivs'ka city council",
      'city': 'Lviv (Frankivskyi rayon)',
      'zipcode': '',
      'location': '49.801,23.9871',
      'latitude': 49.801,
      'longitude': 23.9871,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': "'s network",
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'ALFA TELECOM s.r.o.',
        'MAROSNET Telecommunication Company LLC',
        'AS44546 ALFATELECOM',
      ],
    },
    {
      'ipaddress': '93.170.123.185',
      'threat_potential_score_pct': 88.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 7,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Lviv',
      'district': "L'vivs'ka city council",
      'city': 'Lviv (Frankivskyi rayon)',
      'zipcode': '',
      'location': '49.801,23.9871',
      'latitude': 49.801,
      'longitude': 23.9871,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': "'s network",
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'ALFA TELECOM s.r.o.',
        'MAROSNET Telecommunication Company LLC',
        'ALFA TELECOM s.r.o.',
        'MAROSNET Telecommunication Company LLC',
        'AS44546 ALFATELECOM',
      ],
    },
    {
      'ipaddress': '93.170.123.60',
      'threat_potential_score_pct': 88.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 7,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Lviv',
      'district': "L'vivs'ka city council",
      'city': 'Lviv (Frankivskyi rayon)',
      'zipcode': '',
      'location': '49.801,23.9871',
      'latitude': 49.801,
      'longitude': 23.9871,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': "'s network",
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'ALFA TELECOM s.r.o.',
        'MAROSNET Telecommunication Company LLC',
        'AS44546 ALFATELECOM',
      ],
    },
    {
      'ipaddress': '93.170.131.108',
      'threat_potential_score_pct': 88.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Novosibirsk Oblast',
      'district': 'Novosibirskiy Rayon',
      'city': 'Novosibirsk',
      'zipcode': '',
      'location': '54.9879,82.913',
      'latitude': 54.9879,
      'longitude': 82.913,
      'timezone_offset': 7,
      'timezone_name': 'Asia/Novosibirsk',
      'ispname': 'ADMAN',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'ALFA TELECOM s.r.o.',
        'Krek Ltd.',
        'ALFA TELECOM s.r.o.',
        'Krek Ltd.',
        'AS44546 ALFATELECOM',
      ],
    },
    {
      'ipaddress': '93.170.169.52',
      'threat_potential_score_pct': 88.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'NL',
      'stateprov': 'Flevoland',
      'district': 'Gemeente Dronten',
      'city': 'Dronten',
      'zipcode': '8254',
      'location': '52.5347,5.72181',
      'latitude': 52.5347,
      'longitude': 5.72181,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Amsterdam',
      'ispname': 'ZOMRO-NL',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'ALFA TELECOM s.r.o.',
        'ITL Company',
        'AS44546 ALFATELECOM',
      ],
    },
    {
      'ipaddress': '94.242.57.45',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 9,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'St.-Petersburg',
      'district': 'St.-Petersburg',
      'city': 'St Petersburg',
      'zipcode': '',
      'location': '59.8657,30.4601',
      'latitude': 59.8657,
      'longitude': 30.4601,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'RNet ISP & veesp.com data-center',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'OOO Fishnet Communications',
        'AS43317 FISHNET AS',
      ],
    },
    {
      'ipaddress': '94.242.59.239',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Moscow',
      'district': 'Moscow',
      'city': 'Moscow',
      'zipcode': '',
      'location': '55.7558,37.6173',
      'latitude': 55.7558,
      'longitude': 37.6173,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'RNet ISP & veesp.com data-center',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS43317 FISHNET AS',
      ],
    },
    {
      'ipaddress': '95.163.107.41',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 4,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Moscow',
      'district': 'North-Eastern Administrative Okrug',
      'city': 'Moscow',
      'zipcode': '',
      'location': '55.8193,37.6474',
      'latitude': 55.8193,
      'longitude': 37.6474,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'Digital Network JSC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'JSC Digital Network',
        'AS12695 DINET AS',
      ],
    },
    {
      'ipaddress': '95.181.171.58',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 1,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'Moscow',
      'district': 'gorod Moskva',
      'city': 'Moscow',
      'zipcode': '',
      'location': '55.7929,37.6661',
      'latitude': 55.7929,
      'longitude': 37.6661,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'QWARTA.RU',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'QWARTA LLC',
        'AS50214 QWARTA',
      ],
    },
    {
      'ipaddress': '95.213.184.10',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 2,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'St.-Petersburg',
      'district': 'gorod Sankt-Peterburg',
      'city': 'St Petersburg',
      'zipcode': '',
      'location': '59.8889,30.3296',
      'latitude': 59.8889,
      'longitude': 30.3296,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'SELECTEL',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'OOO Network of data-centers Selectel',
        'OOO Network of data-centers Selectel',
        'AS49505 SELECTEL',
      ],
    },
    {
      'ipaddress': '95.213.195.123',
      'threat_potential_score_pct': 94.2,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 4,
      'blacklist_observations': 110,
      'country': 'RU',
      'stateprov': 'St.-Petersburg',
      'district': 'gorod Sankt-Peterburg',
      'city': 'St Petersburg',
      'zipcode': '',
      'location': '59.8889,30.3296',
      'latitude': 59.8889,
      'longitude': 30.3296,
      'timezone_offset': 3,
      'timezone_name': 'Europe/Moscow',
      'ispname': 'SELECTEL',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'OOO Network of data-centers Selectel',
        'AS49505 SELECTEL',
      ],
    },
    {
      'ipaddress': '95.46.114.205',
      'threat_potential_score_pct': 88.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Lviv',
      'district': "L'vivs'ka city council",
      'city': 'Lviv (Frankivskyi rayon)',
      'zipcode': '',
      'location': '49.801,23.9871',
      'latitude': 49.801,
      'longitude': 23.9871,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': "'s network",
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'ALFA TELECOM s.r.o.',
        'MAROSNET Telecommunication Company LLC',
        'AS44546 ALFATELECOM',
      ],
    },
    {
      'ipaddress': '95.46.114.80',
      'threat_potential_score_pct': 88.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Lviv',
      'district': "L'vivs'ka city council",
      'city': 'Lviv (Frankivskyi rayon)',
      'zipcode': '',
      'location': '49.801,23.9871',
      'latitude': 49.801,
      'longitude': 23.9871,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': "'s network",
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'ALFA TELECOM s.r.o.',
        'MAROSNET Telecommunication Company LLC',
        'AS44546 ALFATELECOM',
      ],
    },
    {
      'ipaddress': '95.46.114.97',
      'threat_potential_score_pct': 88.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 5,
      'blacklist_observations': 110,
      'country': 'UA',
      'stateprov': 'Lviv',
      'district': "L'vivs'ka city council",
      'city': 'Lviv (Frankivskyi rayon)',
      'zipcode': '',
      'location': '49.801,23.9871',
      'latitude': 49.801,
      'longitude': 23.9871,
      'timezone_offset': 2,
      'timezone_name': 'Europe/Kiev',
      'ispname': "'s network",
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'ALFA TELECOM s.r.o.',
        'MAROSNET Telecommunication Company LLC',
        'AS44546 ALFATELECOM',
      ],
    },
    {
      'ipaddress': '95.85.19.195',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'ransomware',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'NL',
      'stateprov': 'North Holland',
      'district': 'Gemeente Amsterdam',
      'city': 'Amsterdam-Zuidoost',
      'zipcode': '1105',
      'location': '52.2959,4.94417',
      'latitude': 52.2959,
      'longitude': 4.94417,
      'timezone_offset': 1,
      'timezone_name': 'Europe/Amsterdam',
      'ispname': 'DigitalOcean, LLC',
      'network_type': [
        'Worldwide Networks',
      ],
      'network_group': [
        'All ASN Networks',
      ],
      'network_name': [
        'AS14061 Digitalocean LLC',
      ],
    },
    {
      'ipaddress': '98.143.148.173',
      'threat_potential_score_pct': 84.8,
      'threat_classification': 'High',
      'blacklist_class': 'unlisted',
      'blacklist_class_cnt': 1,
      'blacklist_network_neighbor_cnt': 3,
      'blacklist_observations': 110,
      'country': 'US',
      'stateprov': 'California',
      'district': 'Los Angeles',
      'city': 'Los Angeles (Downtown)',
      'zipcode': '90014',
      'location': '34.0435,-118.252',
      'latitude': 34.0435,
      'longitude': -118.252,
      'timezone_offset': -8,
      'timezone_name': 'America/Los_Angeles',
      'ispname': 'QuadraNet Enterprises LLC',
      'network_type': [
        'Worldwide Networks',
        'Cloud Services Platform',
      ],
      'network_group': [
        'All ASN Networks',
        'Commercial Cloud Provider',
      ],
      'network_name': [
        'QuadraNet US',
        'QuadraNet US',
        'QuadraNet US',
        'AS8100 QuadraNet Enterprises LLC',
        'QuadraNet Enterprises LLC',
      ],
    },
  ],
}]);
